# Generated by Django 5.2.9 on 2025-12-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('x', models.IntegerField(default=50)),
                ('y', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=220)),
                ('height', models.IntegerField(default=220)),
                ('color', models.CharField(choices=[('#C7A4FF', 'Soft Purple'), ('#FFF176', 'Electric Yellow'), ('#FF8A80', 'Soft Coral'), ('#A5D6A7', 'Mint'), ('#80CBC4', 'Teal')], default='#FFF176', max_length=7)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. work,ideas)', max_length=255)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
    ]
