# Generated by Django 5.2.9 on 2025-12-04 12:39

from django.db import migrations


def create_default_boards(apps, schema_editor):
    """Create default board for each user with notes"""
    Note = apps.get_model('notes', 'Note')
    Board = apps.get_model('notes', 'Board')
    User = apps.get_model('auth', 'User')
    
    # Get all users who have notes
    users_with_notes = Note.objects.values_list('user_id', flat=True).distinct()
    
    for user_id in users_with_notes:
        # Create a default board for this user
        board = Board.objects.create(
            user_id=user_id,
            name="My Board"
        )
        # Assign all their notes to this board
        Note.objects.filter(user_id=user_id, board__isnull=True).update(board=board)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_board_note_board'),
    ]

    operations = [
        migrations.RunPython(create_default_boards, migrations.RunPython.noop),
    ]
