# Generated by Django 5.2.9 on 2025-12-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20251204_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.board'),
        ),
    ]
