# Generated by Django 5.2.9 on 2025-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'No tag'), ('work', 'Work'), ('idea', 'Idea'), ('focus', 'Focus'), ('personal', 'Personal'), ('todo', 'To Do')], default='', help_text='Single tag for the note', max_length=50),
        ),
    ]
